name: CI/CD Pipeline

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test-and-lint:
    runs-on: [self-hosted, linux]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
      
 # Sem teste     
    # - name: Run tests
    #   run: npm test

  deploy:
    needs: test-and-lint
    runs-on: [self-hosted, linux]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    - name: Install dependencies
      run: npm ci

    - name: Preserve .env file
      run: |
        # Verifique se o .env já existe na raiz do projeto antes de criar um novo
        if [ ! -f .env ]; then
          echo ".env file not found. Using .env.example to create .env."
          cp .env.example .env
        else
          echo ".env file already exists. Skipping creation."
        fi
    
    - name: Deploy with PM2
      run: |
        # Se a aplicação já estiver configurada no PM2, apenas reinicie
        pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js