name: CI/CD

on:  
  push:  
    branches: [ master ]  

jobs:  
  build:  
    runs-on: self-hosted  
    steps:  
      - name: Clonar repositório  
        uses: actions/checkout@v3  

      - name: Instalar dependências  
        run: npm install  

      - name: Rodar lint  
        run: npm run lint  

      - name: Rodar testes  
        run: npm test  

      - name: Fazer deploy  
        run: |  
          pm2 restart /carteira_vacinacao  # Substitua "app" pelo nome do seu processo no PM2  
